# Generated by Django 3.2.7 on 2021-09-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_per_night', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('guest_capacity', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('internet', models.BooleanField()),
                ('breakfast', models.BooleanField()),
                ('air_conditioned', models.BooleanField()),
                ('pets_allowed', models.BooleanField()),
                ('room_cleaning', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
