# Generated by Django 3.2.7 on 2021-09-25 05:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='rooms'),
        ),
    ]
